name: 🏭 Cut Mod Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Semver Bump Type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  cut_release:
    name: "Cut Release"
    uses: open-goal/mod-bundling-tools/.github/workflows/mod-bundler.yml@v1
    with:
      semverBump: ${{ inputs.bump }}
      metadataName: "HeroMode+ | A Jak II Overhaul"
      metadataDescription: "Overhauls Jak II's difficulty, but with a twist! Adds weapon mods, custom modifiers, hero mode changes, and various other things to find! Are you up for the challenge?"
      metadataSupportedGames: "jak2"
      metadataAuthors: "Kraken"
      metadataTags: "challenge,gameplay-mod"
      metadataWebsiteUrl: "https://github.com/RealOfficialKraken/updated-HeroModePlus"
      skipMacOS: true
      skipLinux: true
      toolingBinaryDir: "out/build/Release/bin"
      gameAssetsDir: "game/assets"
      copyEntireBinaryDir: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
